import {Items} from './home';

export const ItemArray: Items[] = [
    {
        id:1234,
        itemName:"Bag",
        imageUrl:"./assets/images/p1.jpg",
        price:100
    },
    {
        id:1235,
        itemName:"Belt",
        imageUrl:"./assets/images/p2.jpg",
        price:200
    },
    {
        id:1236,
        itemName:"Bag",
        imageUrl:"./assets/images/p3.jpg",
        price:300
    },
    {
        id:1237,
        itemName:"Bag",
        imageUrl:"./assets/images/p4.jpg",
        price:240
    },
    {
        id:1238,
        itemName:"Bag",
        imageUrl:"./assets/images/p4.jpg",
        price:2410
    },
    {
        id:122347,
        itemName:"Bag",
        imageUrl:"./assets/images/p4.jpg",
        price:2440
    },
    {
        id:12337,
        itemName:"Bag",
        imageUrl:"./assets/images/p4.jpg",
        price:12
    },
    {
        id:111,
        itemName:"Bag",
        imageUrl:"./assets/images/p4.jpg",
        price:12
    },
    {
        id:2222,
        itemName:"Bag",
        imageUrl:"./assets/images/p4.jpg",
        price:12
    }
];